"""empty message

Revision ID: 054472e6a0d4
Revises: d85d1e46b18b
Create Date: 2022-03-30 12:48:13.455868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '054472e6a0d4'
down_revision = 'd85d1e46b18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follower', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
