"""empty message

Revision ID: 17488ff56414
Revises: f5fb04282117
Create Date: 2022-03-30 10:33:39.174142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17488ff56414'
down_revision = 'f5fb04282117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
