"""empty message

Revision ID: 17e6689850e9
Revises: 17468e134ddd
Create Date: 2022-03-30 14:02:58.451630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17e6689850e9'
down_revision = '17468e134ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=600), nullable=True))
    op.drop_column('user', 'Bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Bio', mysql.VARCHAR(length=600), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
