"""empty message

Revision ID: 20de6fd0c948
Revises: ce98eca671a2
Create Date: 2022-03-29 01:53:16.584969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20de6fd0c948'
down_revision = 'ce98eca671a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('Bio', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Bio')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
