"""empty message

Revision ID: 4db415f28703
Revises: 17488ff56414
Create Date: 2022-03-30 10:41:07.610008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db415f28703'
down_revision = '17488ff56414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('follower', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follower', 'created_at')
    op.drop_column('follower', 'id')
    # ### end Alembic commands ###
