"""empty message

Revision ID: 51f7e74211a3
Revises: fb0b4ef40058
Create Date: 2022-03-29 10:23:01.300501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51f7e74211a3'
down_revision = 'fb0b4ef40058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codeet', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('codeet', 'text',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('codeet', 'text',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('codeet', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
