"""empty message

Revision ID: 588d03f7ae09
Revises: 07cee049f3b9
Create Date: 2022-03-31 19:28:46.635478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588d03f7ae09'
down_revision = '07cee049f3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'id')
    # ### end Alembic commands ###
