"""empty message

Revision ID: 7b16cf346bda
Revises: 9e8c66caa733
Create Date: 2022-03-28 15:37:47.030500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b16cf346bda'
down_revision = '9e8c66caa733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=True))
    op.drop_column('user', 'unsername')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unsername', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
