"""empty message

Revision ID: 86b84ef41bc7
Revises: 3fa951ac61ec
Create Date: 2022-03-30 14:26:42.283602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86b84ef41bc7'
down_revision = '3fa951ac61ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Bio', sa.String(length=600), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', mysql.VARCHAR(length=600), nullable=True))
    op.drop_column('user', 'Bio')
    # ### end Alembic commands ###
