"""empty message

Revision ID: c1cfc0e395ef
Revises: 324e0470ce1c
Create Date: 2022-04-03 01:00:10.584109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cfc0e395ef'
down_revision = '324e0470ce1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('codeet_ibfk_1', 'codeet', type_='foreignkey')
    op.create_foreign_key(None, 'codeet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codeet', type_='foreignkey')
    op.create_foreign_key('codeet_ibfk_1', 'codeet', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
